### ISSUE TITLE
Pick a unique name

### ISSUE THREAD

**Issue by hakanai** [Draco-lang/Language-suggestions#96]
https://en.wikipedia.org/wiki/Draco_(programming_language)

**Comment by LPeter1997** [comment]
Sorry but we had a [voting](https://github.com/Draco-lang/Language-suggestions/issues/81) and discussion - on the Discord server - about the name, the current name is considered permanent. We were well aware of the collision at the time of choosing the name, but since it's a fairly unknown language discontinued more than 30 years ago, we decided we can safely use the name.

**Comment by thinker227** [comment]
We considered this when first discussing the name, and we came to the conclusion that the already existing language is likely old and obscure enough for the naming overlap to not be a significant issue.

"It's a shareware PL for a computer that hasn't been around for 30 years thats main use was to port a 40 year old game"
